stages:
  feature_engineering:
    cmd: python3 -m service.features
    deps:
      - data/raw/
      - service/features.py
    outs:
      - data/features.csv
  train:
    cmd: python3 -m service.train
    deps:
      - data/features.csv
      - service/train.py
    params:
      - iterations
      - learning_rate
    outs:
      - models/catboost_model.cbm